package com.abhibot.virtualtrading;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.nio.*;import java.text.*;import java.util.*;import java.util.concurrent.TimeUnit;import okhttp3.*;import org.json.*;

public class MainActivity extends Activity {
 private LinearLayout root; private TextView live; private WebSocket ws; private final String[] names={"NIFTY 50","BANK NIFTY","SENSEX","FINNIFTY"}; private final Map<String,Double> ltp=new HashMap<>(); private final String PREF="abhibot";
 public void onCreate(Bundle b){super.onCreate(b);showHome();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(25,25,25));v.setPadding(8,8,8,8);return v;}
 Button btn(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setOnClickListener(l);return b;}
 void base(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,24);root.setBackgroundColor(Color.WHITE);sv.addView(root);setContentView(sv);}
 void showHome(){base();TextView h=t("AbhiBoT 2.0",28);h.setTypeface(null,1);root.addView(h);root.addView(t("Live Market • Paper Trading",14));live=t("● LIVE DATA: DISCONNECTED",13);live.setTextColor(Color.rgb(210,50,50));root.addView(live);root.addView(t("VIRTUAL BALANCE  ₹1,00,000.00",24));root.addView(t("Markets",24));for(String n:names){Button b=btn(n+"   •   LTP —",v->trade(n));root.addView(b);ltp.put(n,0.0);}root.addView(t("AbhiBoT",24));root.addView(btn("Options / Option Chain",v->optionChain()));root.addView(btn("Watchlist",v->watchlist()));root.addView(btn("Start Trade",v->trade("NIFTY 50")));root.addView(btn("Indicators / Pine Lab",v->indicators()));root.addView(btn("Profile / Live Data Settings",v->settings()));}
 void nav(String title){base();Button back=btn("‹ Back",v->showHome());root.addView(back);TextView h=t(title,26);h.setTypeface(null,1);root.addView(h);}
 void watchlist(){nav("Watchlist");for(String n:names)root.addView(btn(n+"   LTP —",v->trade(n)));root.addView(t("Next: symbol search + instrument master + live multi-symbol subscriptions.",14));}
 void optionChain(){nav("Option Chain");root.addView(t("NIFTY / BANKNIFTY / SENSEX",22));root.addView(t("Next: live strikes, CE/PE LTP, OI, Change in OI, IV and Greeks.",15));}
 void indicators(){nav("Pine-style Indicator Lab");EditText e=new EditText(this);e.setGravity(Gravity.TOP);e.setMinLines(12);e.setText("// AbhiBoT Indicator\nema9 = ema(close, 9)\nema15 = ema(close, 15)\nbuy = crossover(ema9, ema15)\nsell = crossunder(ema9, ema15)");root.addView(e);root.addView(btn("SAVE INDICATOR",v->getPreferences(0).edit().putString("script",e.getText().toString()).apply()));root.addView(t("Pine compatibility will be implemented in stages; Pine is not executed directly inside this APK.",14));}
 void settings(){nav("Live Data Settings");EditText c=new EditText(this);c.setHint("Dhan Client ID");root.addView(c);EditText tok=new EditText(this);tok.setHint("Dhan Access Token");tok.setInputType(129);root.addView(tok);EditText sid=new EditText(this);sid.setHint("NIFTY Security ID");root.addView(sid);root.addView(btn("SAVE & CONNECT",v->connect(c.getText().toString().trim(),tok.getText().toString().trim(),sid.getText().toString().trim())));root.addView(t("Live feed uses DhanHQ WebSocket v2. Credentials and instrument mapping are required.",14));}
 void trade(String n){double p=ltp.get(n);Toast.makeText(this,p>0?"Paper trade "+n+" @ ₹"+money(p):"Live LTP unavailable for "+n,Toast.LENGTH_SHORT).show();}
 String money(double x){NumberFormat f=NumberFormat.getNumberInstance(new Locale("en","IN"));f.setMinimumFractionDigits(2);f.setMaximumFractionDigits(2);return f.format(x);}
 void connect(String client,String token,String sec){if(client.isEmpty()||token.isEmpty()||sec.isEmpty()){Toast.makeText(this,"Client ID, token and Security ID required",Toast.LENGTH_SHORT).show();return;}if(ws!=null)ws.close(1000,"reconnect");String u="wss://api-feed.dhan.co?version=2&token="+token+"&clientId="+client+"&authType=2";OkHttpClient hc=new OkHttpClient.Builder().readTimeout(0,TimeUnit.MILLISECONDS).build();ws=hc.newWebSocket(new Request.Builder().url(u).build(),new WebSocketListener(){public void onOpen(WebSocket s,Response r){runOnUiThread(()->{live.setText("● LIVE DATA: CONNECTED");live.setTextColor(Color.rgb(20,160,80));});try{JSONObject x=new JSONObject();x.put("RequestCode",15);x.put("InstrumentCount",1);JSONArray a=new JSONArray();JSONObject i=new JSONObject();i.put("ExchangeSegment","IDX_I");i.put("SecurityId",sec);a.put(i);x.put("InstrumentList",a);s.send(x.toString());}catch(Exception e){}}public void onMessage(WebSocket s,okio.ByteString d){byte[] b=d.toByteArray();if(b.length>=13&&(b[0]&255)==2){double p=ByteBuffer.wrap(b).order(ByteOrder.LITTLE_ENDIAN).getFloat(8);ltp.put("NIFTY 50",p);}}public void onFailure(WebSocket s,Throwable e,Response r){runOnUiThread(()->{live.setText("● LIVE DATA: ERROR / DISCONNECTED");live.setTextColor(Color.rgb(210,50,50));});}});}
 public void onDestroy(){if(ws!=null)ws.close(1000,"closed");super.onDestroy();}
}
